chore: update build action to use podman and cache builds

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -1,3 +1,4 @@
+name: Build Container
 on:
   push:
     branches:
@@ -7,24 +8,70 @@ on:
   workflow_dispatch:
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04 # uses podman from 24.04 or later
     env:
+      REGISTRY: ghcr.io
       IMAGE: ghcr.io/${{ github.repository_owner }}/duplicacy
+      IMGCACHE_PATH: image_cache.tar
+      # building using docker format is required to make builds
+      # find cached build layers after a save/load cycle
+      BUILDAH_FORMAT: docker
     steps:
-      - uses: docker/login-action@v2.2.0
+      - env:
+          USERNAME: ${{ github.actor }}
+          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
+        run: printenv PASSWORD | podman login -v ${{ env.REGISTRY }} -u "$USERNAME" --password-stdin
+
+      - id: restore-cache
+        uses: actions/cache/restore@v4
         with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      - uses: actions/checkout@v3
-      - run: DOCKER_BUILDKIT=1 docker build -f Containerfile -t ${{ env.IMAGE }} .
-      - name: docker tag ...
+          # we can't precalculate the hash for a key so
+          # set an invalid key and fall back to the most recent cache
+          key: image-cache-INVALID
+          restore-keys: image-cache-
+          path: ${{ env.IMGCACHE_PATH }}
+
+      - name: Import images from cache
+        # skip step if no cache was restored
+        if: steps.restore-cache.outputs.cache-matched-key != ''
+        continue-on-error: true
+        run: |
+          podman load -i "${IMGCACHE_PATH:?}" \
+            || echo "::warning::Failure while importing images from cache"
+
+      - uses: actions/checkout@v4
+
+      - run: podman build -t ${{ env.IMAGE }} .
+
+      - name: Add image version tag
         run: |
           set -x
           VERSION=$(
-            docker run --rm -i ${{ env.IMAGE }} help \
+            podman run --rm -i ${{ env.IMAGE }} help \
               | awk '/^VERSION/ { l = NR + 1 }; NR == l && $1 ~ /^[0-9.]+$/ { print $1 }'
           )
           [ -n "$VERSION" ] || exit
-          docker tag ${{ env.IMAGE }} ${{ env.IMAGE }}:"$VERSION"
-      - run: docker push -a ${{ env.IMAGE }}
+          podman tag ${{ env.IMAGE }} ${{ env.IMAGE }}:"$VERSION"
+
+      - run: podman image inspect --format '{{ range .RepoTags }}{{ . }} {{ end }}'
+          ${{ env.IMAGE }} | xargs -n 1 podman push
+
+      - if: ${{ !cancelled() }} # runs even if previous steps failed
+        run: podman logout ${{ env.REGISTRY }}
+
+      - id: export-cache
+        name: Export images to cache
+        continue-on-error: true
+        run: |
+          rm -f "${IMGCACHE_PATH:?}"
+          echo "Saving Images:"
+          podman image list --all --format '{{ range .RepoTags }}{{ . }}\n{{ else }}{{ .ID }}{{ end }}' | sort -u \
+            | tee /dev/stderr \
+            | xargs podman save -m -o "${IMGCACHE_PATH:?}" \
+            || echo "::error::Failure while exporting images to cache"
+
+      - uses: actions/cache/save@v4
+        if: steps.export-cache.outcome == 'success' && !endsWith(steps.restore-cache.outputs.cache-matched-key, hashFiles(env.IMGCACHE_PATH))
+        with:
+          key: image-cache-${{ hashFiles(env.IMGCACHE_PATH) }}
+          path: ${{ env.IMGCACHE_PATH }}
